import { describe, it, expect } from 'vitest';
import { generateInterface, generateIndexFile } from '../../../src/core/generator/ts-interface';
import { DTOClass } from '../../../src/types/dto.types';

describe('ts-interface', () => {
  describe('generateInterface', () => {
    it('should generate basic interface', () => {
      const dto: DTOClass = {
        className: 'UserDto',
        packageName: 'com.example',
        fields: [
          { name: 'id', javaType: 'Long', tsType: 'number', nullable: true, isEnum: false, annotations: [] },
          { name: 'name', javaType: 'String', tsType: 'string', nullable: false, isEnum: false, annotations: ['NotNull'] }
        ],
        imports: [],
        isEnum: false,
        filePath: 'UserDto.java'
      };

      const result = generateInterface(dto, [dto]);
      expect(result).toContain('export interface UserDto {');
      expect(result).toContain('id?: number;');
      expect(result).toContain('name: string;');
    });

    it('should quote reserved words', () => {
      const dto: DTOClass = {
        className: 'TestDto',
        packageName: 'com.example',
        fields: [
          { name: 'class', javaType: 'String', tsType: 'string', nullable: true, isEnum: false, annotations: [] }
        ],
        imports: [],
        isEnum: false,
        filePath: 'TestDto.java'
      };

      const result = generateInterface(dto, [dto]);
      expect(result).toContain("'class'?: string;");
    });

    it('should quote special characters', () => {
      const dto: DTOClass = {
        className: 'TestDto',
        packageName: 'com.example',
        fields: [
          { name: 'field-name', jsonName: 'field-name', javaType: 'String', tsType: 'string', nullable: true, isEnum: false, annotations: [] }
        ],
        imports: [],
        isEnum: false,
        filePath: 'TestDto.java'
      };

      const result = generateInterface(dto, [dto]);
      expect(result).toContain("'field-name'?: string;");
    });

    it('should add extends clause', () => {
      const parentDto: DTOClass = {
        className: 'BaseDto',
        packageName: 'com.example',
        fields: [{ name: 'id', javaType: 'Long', tsType: 'number', nullable: true, isEnum: false, annotations: [] }],
        imports: [],
        isEnum: false,
        filePath: 'BaseDto.java'
      };

      const childDto: DTOClass = {
        className: 'ChildDto',
        packageName: 'com.example',
        fields: [{ name: 'name', javaType: 'String', tsType: 'string', nullable: true, isEnum: false, annotations: [] }],
        imports: [],
        extends: 'BaseDto',
        parentFields: parentDto.fields,
        isEnum: false,
        filePath: 'ChildDto.java'
      };

      const result = generateInterface(childDto, [parentDto, childDto]);
      expect(result).toContain('import { BaseDto }');
      expect(result).toContain('export interface ChildDto extends BaseDto {');
      expect(result).toContain('name?: string;');
      expect(result).not.toContain('id');
    });

    it('should add JsonAlias comment', () => {
      const dto: DTOClass = {
        className: 'TestDto',
        packageName: 'com.example',
        fields: [
          { 
            name: 'phone', 
            jsonAliases: ['mobile', 'cell'],
            javaType: 'String', 
            tsType: 'string', 
            nullable: true, 
            isEnum: false, 
            annotations: [] 
          }
        ],
        imports: [],
        isEnum: false,
        filePath: 'TestDto.java'
      };

      const result = generateInterface(dto, [dto]);
      expect(result).toContain('/** Also accepts: mobile, cell */');
    });
  });

  describe('generateIndexFile', () => {
    it('should generate index file with all exports', () => {
      const classes: DTOClass[] = [
        { className: 'UserDto', packageName: '', fields: [], imports: [], isEnum: false, filePath: '' },
        { className: 'OrderDto', packageName: '', fields: [], imports: [], isEnum: false, filePath: '' },
        { className: 'StatusEnum', packageName: '', fields: [], imports: [], isEnum: true, filePath: '' }
      ];

      const result = generateIndexFile(classes);
      expect(result).toContain('// Auto-generated by Spring2TS');
      expect(result).toContain('export * from \'./UserDto\';');
      expect(result).toContain('export * from \'./OrderDto\';');
      expect(result).toContain('export * from \'./StatusEnum\';');
    });
  });
});