import { DTOClass } from '../../types/dto.types';

// TypeScript reserved words and keywords that need quoting
const RESERVED_WORDS = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
  'default', 'delete', 'do', 'else', 'enum', 'export', 'extends',
  'false', 'finally', 'for', 'function', 'if', 'import', 'in',
  'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with',
  'implements', 'interface', 'let', 'package', 'private', 'protected',
  'public', 'static', 'yield', 'abstract', 'as', 'async', 'await',
  'constructor', 'declare', 'from', 'get', 'module', 'namespace',
  'of', 'require', 'set', 'type', 'types',
]);

function formatPropertyName(propertyName: string): string {
  if (RESERVED_WORDS.has(propertyName)) {
    return `'${propertyName}'`;
  }
  const validIdentifier = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
  if (!validIdentifier.test(propertyName)) {
    return `'${propertyName}'`;
  }
  return propertyName;
}

export function generateInterface(dto: DTOClass, allClasses: DTOClass[]): string {
  const lines: string[] = [];
  const referencedTypes = new Set<string>();
  
  if (dto.extends) referencedTypes.add(dto.extends);
  
  for (const field of dto.fields) {
    const matches = field.tsType.match(/\b([A-Z]\w+)\b/g);
    if (matches) {
      matches.forEach(t => {
        if (t !== dto.className && allClasses.some(c => c.className === t)) {
          referencedTypes.add(t);
        }
      });
    }
  }
  
  if (referencedTypes.size > 0) {
    const imports = Array.from(referencedTypes).sort();
    lines.push(`import { ${imports.join(', ')} } from './${imports[0]}';`);
    lines.push('');
  }
  
  const extendsClause = dto.extends ? ` extends ${dto.extends}` : '';
  lines.push(`export interface ${dto.className}${extendsClause} {`);
  
  const parentFieldNames = new Set(dto.parentFields?.map(f => f.jsonName || f.name) || []);
  const processedFields = new Set<string>();
  
  for (const field of dto.fields) {
    // ✅ Skip @JsonIgnore fields
    if (field.jsonIgnore) {
      continue;
    }
    
    const rawPropertyName = field.jsonName || field.name;
    
    if (parentFieldNames.has(rawPropertyName) || processedFields.has(rawPropertyName)) continue;
    processedFields.add(rawPropertyName);
    
    // ✅ Add Jackson warnings as comments
    if (field.jacksonWarnings && field.jacksonWarnings.length > 0) {
      for (const warning of field.jacksonWarnings) {
        lines.push(`  /** ⚠️ ${warning} */`);
      }
    }
    
    // ✅ Add @JsonAlias comment
    if (field.jsonAliases && field.jsonAliases.length > 0) {
      lines.push(`  /** Also accepts: ${field.jsonAliases.join(', ')} */`);
    }
    
    const optional = field.nullable ? '?' : '';
    const fieldType = field.isEnum && field.enumName ? field.enumName : field.tsType;
    const propertyName = formatPropertyName(rawPropertyName);
    
    lines.push(`  ${propertyName}${optional}: ${fieldType};`);
  }
  
  lines.push('}');
  return lines.join('\n');
}

export function generateIndexFile(classes: DTOClass[]): string {
  const lines: string[] = ['// Auto-generated by Spring2TS', '// DO NOT EDIT MANUALLY', ''];
  for (const dto of classes) lines.push(`export * from './${dto.className}';`);
  return lines.join('\n');
}