import { DTOClass } from '../../types/dto.types';

// TypeScript reserved words and keywords that need quoting
const RESERVED_WORDS = new Set([
  // Reserved keywords
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
  'default', 'delete', 'do', 'else', 'enum', 'export', 'extends',
  'false', 'finally', 'for', 'function', 'if', 'import', 'in',
  'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with',
  // Strict mode reserved
  'implements', 'interface', 'let', 'package', 'private', 'protected',
  'public', 'static', 'yield',
  // Future reserved
  'abstract', 'as', 'async', 'await', 'constructor', 'declare',
  'from', 'get', 'module', 'namespace', 'of', 'require', 'set',
  'type', 'types',
]);

/**
 * Check if a property name needs quotes
 */
function needsQuotes(propertyName: string): boolean {
  // Always quote if it's a reserved word
  if (RESERVED_WORDS.has(propertyName)) {
    return true;
  }
  
  // Always quote if it contains special characters
  // Valid identifier: letters, numbers, underscore, dollar sign
  const validIdentifier = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
  if (!validIdentifier.test(propertyName)) {
    return true;
  }
  
  return false;
}

/**
 * Format a property name (add quotes if needed)
 */
function formatPropertyName(propertyName: string): string {
  if (needsQuotes(propertyName)) {
    const escaped = propertyName.replace(/'/g, "\\'");
    return `'${escaped}'`;
  }
  return propertyName;
}

export function generateInterface(dto: DTOClass, allClasses: DTOClass[]): string {
  const lines: string[] = [];
  
  const referencedTypes = new Set<string>();
  
  // Add parent class to imports if needed
  if (dto.extends) {
    referencedTypes.add(dto.extends);
  }
  
  for (const field of dto.fields) {
    const matches = field.tsType.match(/\b([A-Z]\w+)\b/g);
    if (matches) {
      matches.forEach(t => {
        if (t !== dto.className && allClasses.some(c => c.className === t)) {
          referencedTypes.add(t);
        }
      });
    }
  }
  
  if (referencedTypes.size > 0) {
    const imports = Array.from(referencedTypes).sort();
    lines.push(`import { ${imports.join(', ')} } from './${imports[0]}';`);
    lines.push('');
  }
  
  // Add extends clause
  const extendsClause = dto.extends ? ` extends ${dto.extends}` : '';
  lines.push(`export interface ${dto.className}${extendsClause} {`);
  
  // Generate only fields that aren't in parent
  const parentFieldNames = new Set(dto.parentFields?.map(f => f.jsonName || f.name) || []);
  
  // Track processed fields to avoid duplicates
  const processedFields = new Set<string>();
  
  for (const field of dto.fields) {
    const rawPropertyName = field.jsonName || field.name;
    
    // Skip fields already defined in parent
    if (parentFieldNames.has(rawPropertyName)) {
      continue;
    }
    
    // Skip if already processed (prevents duplicates)
    if (processedFields.has(rawPropertyName)) {
      continue;
    }
    processedFields.add(rawPropertyName);
    
    const optional = field.nullable ? '?' : '';
    const fieldType = field.isEnum && field.enumName ? field.enumName : field.tsType;
    
    // Format property name (add quotes for reserved words or special characters)
    const propertyName = formatPropertyName(rawPropertyName);
    
    // Add comment for aliases if present
    if (field.jsonAliases && field.jsonAliases.length > 0) {
      lines.push(`  /** Also accepts: ${field.jsonAliases.join(', ')} */`);
    }
    
    lines.push(`  ${propertyName}${optional}: ${fieldType};`);
  }
  
  lines.push('}');
  
  return lines.join('\n');
}

export function generateIndexFile(classes: DTOClass[]): string {
  const lines: string[] = [];
  
  lines.push('// Auto-generated by Spring2TS');
  lines.push('// DO NOT EDIT MANUALLY');
  lines.push('');
  
  for (const dto of classes) {
    lines.push(`export * from './${dto.className}';`);
  }
  
  return lines.join('\n');
}